name: Poryecto RegistrarProducto Pipeline

on:
  workflow_dispatch:

    jobs:
      build:
        runs-on: ubuntu-22.04

        steps:
          - name: Prueba inicial
            run: echo "workflow para el proyecto final"
