name: Proyecto Final Pipeline

on:
  push:
    branches:
    - main

  jobs:
      build:
        runs-on: ubuntu-22.04

        steps:
          - name: Proyecto Final
            run: echo "workflow para el proyecto final"
