name: Proyecto Final Pipeline

on:
  workflow_dispatch:
    inputs:
      tags:
        description:  'Tag del Proyecto'
        required: true
        default: '@automation-api'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Proyecto final
        run: echo "workflow proyecto"

      - name: Instalacion de Java 17
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Pruebas
        uses: mvn clean test -Dkarate.tags=${{ inputs.tags }}

      - name: Visualizar reporte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: target/karate-reports